const CART_PRODUCT_GET_ASYNC = 'CART_PRODUCT_GET_ASYNC';
const CART_CHECKOUT = 'CART_CHECKOUT';
const CART_CHECKOUT_ASYNC = 'CART_CHECKOUT_ASYNC';
const CART_DELIVERY = 'CART_DELIVERY';
const CART_PAYMENT = 'CART_PAYMENT';

module.exports = {
    CART_PRODUCT_GET_ASYNC,
    CART_CHECKOUT,
    CART_CHECKOUT_ASYNC,
    CART_DELIVERY,
    CART_PAYMENT
}