const ORDER_CREATE = 'ORDER_CREATE';
const ORDER_GET = 'ORDER_GET';
const ORDER_EDIT_UPDATE = 'ORDER_EDIT_UPDATE'
const ORDER_LIST = 'ORDER_LIST';
const ORDER_SEARCH = 'ORDER_SEARCH';
const ORDER_DELETE = 'ORDER_DELETE';
const ORDER_DELETE_COMMIT = 'ORDER_DELETE_COMMIT';

const ORDER_CREATE_ASYNC = 'ORDER_CREATE_ASYNC';
const ORDER_GET_ASYNC = 'ORDER_GET_ASYNC';
const ORDER_EDIT_UPDATE_ASYNC = 'ORDER_EDIT_UPDATE_ASYNC';
const ORDER_LIST_ASYNC = 'ORDER_LIST_ASYNC';
const ORDER_SEARCH_ASYNC = 'ORDER_SEARCH_ASYNC';
const ORDER_DELETE_ASYNC = 'ORDER_DELETE_ASYNC';
const ORDER_DELETE_COMMIT_ASYNC = 'ORDER_DELETE_COMMIT_ASYNC';

const ORDER_PRODUCT_ITEMS = 'ORDER_PRODUCT_ITEMS';
const ORDER_PRODUCT_ITEMS_ASYNC = 'ORDER_PRODUCT_ITEMS_ASYNC';

module.exports = {
    ORDER_CREATE,
    ORDER_CREATE_ASYNC,
    ORDER_GET,
    ORDER_GET_ASYNC,
    ORDER_EDIT_UPDATE,
    ORDER_EDIT_UPDATE_ASYNC,
    ORDER_LIST,
    ORDER_LIST_ASYNC,
    ORDER_SEARCH,
    ORDER_SEARCH_ASYNC,
    ORDER_DELETE,
    ORDER_DELETE_ASYNC,
    ORDER_DELETE_COMMIT,
    ORDER_DELETE_COMMIT_ASYNC,
    ORDER_PRODUCT_ITEMS,
    ORDER_PRODUCT_ITEMS_ASYNC
}