const PRODUCT_CREATE = 'PRODUCT_CREATE';
const PRODUCT_EDIT = 'PRODUCT_EDIT';
const PRODUCT_EDIT_UPDATE = 'PRODUCT_EDIT_UPDATE'
const PRODUCT_LIST = 'PRODUCT_LIST';
const PRODUCT_SEARCH = 'PRODUCT_SEARCH';
const PRODUCT_DELETE = 'PRODUCT_DELETE';
const PRODUCT_DELETE_COMMIT = 'PRODUCT_DELETE_COMMIT';

const PRODUCT_CREATE_ASYNC = 'PRODUCT_CREATE_ASYNC';
const PRODUCT_EDIT_ASYNC = 'PRODUCT_EDIT_ASYNC';
const PRODUCT_EDIT_UPDATE_ASYNC = 'PRODUCT_EDIT_UPDATE_ASYNC';
const PRODUCT_LIST_ASYNC = 'PRODUCT_LIST_ASYNC';
const PRODUCT_SEARCH_ASYNC = 'PRODUCT_SEARCH_ASYNC';
const PRODUCT_DELETE_ASYNC = 'PRODUCT_DELETE_ASYNC';
const PRODUCT_DELETE_COMMIT_ASYNC = 'PRODUCT_DELETE_COMMIT_ASYNC';

const PRODUCT_CART_UPDATE = 'PRODUCT_CART_UPDATE';

const START_LOADING = 'START_LOADING';
const CLEAN_RESULT = 'CLEAN_RESULT';
const CLEAN_MESSAGE = 'CLEAN_MESSAGE';
const CLEAN_LOADING = 'CLEAN_LOADING';
const CLEAN_SEARCH_PRODUCTS = 'CLEAN_SEARCH_PRODUCTS';

module.exports = {
    PRODUCT_CREATE,
    PRODUCT_CREATE_ASYNC,
    PRODUCT_EDIT,
    PRODUCT_EDIT_ASYNC,
    PRODUCT_EDIT_UPDATE,
    PRODUCT_EDIT_UPDATE_ASYNC,
    PRODUCT_LIST,
    PRODUCT_LIST_ASYNC,
    PRODUCT_SEARCH,
    PRODUCT_SEARCH_ASYNC,
    PRODUCT_DELETE,
    PRODUCT_DELETE_ASYNC,
    PRODUCT_DELETE_COMMIT,
    PRODUCT_DELETE_COMMIT_ASYNC,
    PRODUCT_CART_UPDATE,
    START_LOADING,
    CLEAN_RESULT,
    CLEAN_MESSAGE,
    CLEAN_LOADING,
    CLEAN_SEARCH_PRODUCTS
}