const CART_PRODUCT_GET = 'CART_PRODUCT_GET';
const UPDATE_CART = 'UPDATE_CART';
const CLEAR_CART = 'CLEAR_CART';
const CART_PRODUCT_GET_ASYNC = 'CART_PRODUCT_GET_ASYNC';
const CART_PRODUCT_REMOVE = 'CART_PRODUCT_REMOVE';
const UPDATE_CART_TOTAL = 'UPDATE_CART_TOTAL'

const CLEAN_RESULT = 'CLEAN_RESULT';
const CLEAN_MESSAGE = 'CLEAN_MESSAGE';
const CLEAN_LOADING = 'CLEAN_LOADING';
const START_LOADING = 'START_LOADING';

export {
    UPDATE_CART,
    CART_PRODUCT_GET,
    CART_PRODUCT_GET_ASYNC,
    CART_PRODUCT_REMOVE,
    UPDATE_CART_TOTAL,
    CLEAR_CART,
    CLEAN_RESULT,
    CLEAN_MESSAGE,
    CLEAN_LOADING,
    START_LOADING
}